cc_library(
	name = "base",
	srcs = glob([
		"*.cpp",
	]),
	hdrs = glob([
		"*.h",
	]),
	linkopts = [
		"-lpthread",
	],
	copts = [
		"-std=c++11",
		"-g",
	],
	visibility = ["//visibility:public"],
)

